# Generated by Django 3.2 on 2021-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_options',
            field=models.CharField(default='4-days', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Household', 'Household'), ('Clothing', 'Clothing'), ('FOOD', 'FOOD')], max_length=100),
        ),
    ]
